name: tidal
version: '1.0-dev'
summary: Pattern language (here for livecoding music)
type: app
description: |
  Language for live coding of pattern
  (c) Alex McLean and contributors, 2018
  Distributed under the terms of the GNU Public license version 3 (or later).
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  tidal:
    command: desktop-launch $SNAP/usr/bin/tidal
    desktop: |

parts:
  tidal:
    source: .
    source-tag: nil
    plugin: nil
    
    build-attributes:
      - no-system-libraries
    
    prepare: |
    
      apt-get update
      add-apt-repository ppa:supercollider/ppa
      apt-get install supercollider
      apt-get install build-essential libsndfile1-dev libsamplerate0-dev \
        liblo-dev libjack-jackd2-dev qjackctl jackd git
      apt-get install -y haskell-platform
    
    build: |
      
      has_wget=$(which wget)
      if [ -f $has_wget ] ; then
        wget https://github.com/atom/atom/releases/download/v1.26.1/atom-amd64.deb
        else 
          echo "The Atom installation script anticipates the presence of wget."
          echo "To continue you may install GNU wget."
          exit 1
      fi
      apt-get install -f atom-amd64.deb
      
      git clone --recursive https://github.com/tidalcycles/Dirt.git Dirt
      cd Dirt
      make clean; make
    
    install: |
        
      has_cabal=$(which cabal)
      if [ -f $has_cabal ] ; then 
          cabal update
          cabal install tidal
        else
          echo "The Tidal installation script anticipates the presence of cabal."
          echo "Please review your Haskell installation."
          echo "To continue you may install the Haskell package manager, cabal."
          exit 2
      fi
    
